modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "craftedcore"
version = "${version}"
displayName = "CraftedCore"
authors = "To_Craft"
description = '''
My libary mod to make mods more compatible with modloaders
'''
#logoFile = ""

[[dependencies.craftedcore]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftedcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.craftedcore]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"
